name: Daily NASA Asteroid ETL

on:
  schedule:
    # cron: 'Minute Stunde Tag Monat Wochentag' (Angabe in UTC-Zeit!)
    # 0 2 * * * bedeutet: Jeden Tag um 02:00 Uhr nachts UTC (03:00 / 04:00 Uhr deutsche Zeit)
    # 1 zum Schluss für jeden Montag
    - cron: '0 2 * * 1'
  workflow_dispatch: # Erlaubt es dir, das Skript jederzeit manuell per Klick auf GitHub zu starten!

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      # 1. Den Code aus dem Repository auf den GitHub-Server laden
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Python auf dem GitHub-Server installieren
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Die benötigten Bibliotheken installieren
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas sqlalchemy psycopg2-binary

      # 4. Das Skript ausführen und die Secrets als Umgebungsvariablen übergeben
      - name: Run ETL Script
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          NEON_DB_URL: ${{ secrets.NEON_DB_URL }}
        run: python lib/python/etl_script.py